// SQL seed is derived from the same catalog and visual registry as local mode.
import { readFile, writeFile } from 'node:fs/promises'
import { RENDER_PRESETS } from '../../shared/renderPresets.js'
const catalog = JSON.parse(
  await readFile(new URL('../catalog.json', import.meta.url), 'utf8'),
)
const sql = (value) => `'${String(value).replaceAll("'", "''")}'`
const statements = [
  '-- Generated by node server/db/generateSeed.js. No credentials.\nbegin;',
]
for (const [key, preset] of Object.entries(RENDER_PRESETS)) {
  const [category, render] = key.split(':')
  statements.push(
    `insert into public.render_variants values (${sql(category)}, ${sql(render)}, ${sql(preset.slot)}) on conflict (visual_category,render_key) do update set slot = excluded.slot;`,
  )
}
for (const v of catalog.vehicles)
  statements.push(
    `insert into public.vehicles(year,make,model,trim,profile) values (${v.year},${sql(v.make)},${sql(v.model)},${sql(v.trim)},${sql(JSON.stringify(v.profile))}::jsonb) on conflict (year,make,model,trim) do nothing;`,
  )
for (const p of catalog.parts)
  statements.push(
    `insert into public.parts(name,type,manufacturer,sku,visual_category,render_key,source_url,fitment_notes,specifications) values (${[p.name, p.visual_category, p.manufacturer, p.sku, p.visual_category, p.render_key, p.source_url, p.fitment_notes, JSON.stringify(p.specifications)].map(sql).join(',')}) on conflict (sku) do nothing;`,
  )
for (const c of catalog.compatibility) {
  const p = catalog.parts.find((p) => p.id === c.part_id),
    v = catalog.vehicles.find((v) => v.id === c.vehicle_id)
  statements.push(
    `insert into public.compatibility(part_id,vehicle_id,car_make,car_model,car_year_range) select p.id,v.id,v.make,v.model,v.year::text from public.parts p cross join public.vehicles v where p.sku=${sql(p.sku)} and v.year=${v.year} and v.make=${sql(v.make)} and v.model=${sql(v.model)} and v.trim=${sql(v.trim)} on conflict (vehicle_id,part_id) do nothing;`,
  )
}
statements.push('commit;')
await writeFile(
  new URL('./seed.sql', import.meta.url),
  statements.join('\n') + '\n',
)
